[[pages]]
path = "Home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/1_TransportationSuite.py"
name = "Transportation Suite"
icon = "ğŸš›"

[[pages]]
path = "pages/2_ShipmentPlanner_Basic.py"
name = "Shipment Planner â€“ Basic"
icon = "ğŸ“¦"

[[pages]]
name = "Advanced Pilots"
icon = "ğŸš€"
is_section = true

[[pages]]
path = "pages/3_ShipmentPlanner_VRP.py"
name = "VRP Optimization"
icon = "ğŸ›»"

[[pages]]
path = "pages/4_ShipmentPlanner_VRPTW.py"
name = "VRPTW â€“ Time Windows"
icon = "â±"

[[pages]]
path = "pages/5_ShipmentPlanner_MultiModal.py"
name = "Multi-Modal Planner"
icon = "ğŸš¢"
